language: rust
rust: stable
sudo: false
script:
  - cargo build --verbose
  - rustdoc --test README.md --extern markov=target/debug/libmarkov.rlib -L target/debug/deps
  - cargo build --verbose --features "getopts"
  - cargo test --verbose --features "getopts"
  - cargo test --doc
notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.pdgn.co:6697/#commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
