[package]

name = "markov"
version = "0.0.30"
description = "A generic markov chain implementation in Rust."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "CC0-1.0"
keywords = ["markov", "chain", "probability"]
documentation = "http://aatxe.github.io/markov/markov/"
repository = "https://github.com/aatxe/markov"
readme = "README.md"

[dependencies]
rand = "*"
